#!/usr/bin/env python3
"""Create a deterministic mock Prompt Vote Lab implementation.

This script is for testing GitHub Actions, safety checks, branch creation, commits,
and PR creation without calling the OpenAI API.

It intentionally writes only:
- lab/index.html
- lab/style.css
- lab/app.js
"""

from __future__ import annotations

import argparse
import html
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--week", required=True)
    parser.add_argument("--candidate-rank", required=True)
    parser.add_argument("--issue-number", required=True)
    parser.add_argument("--voted-prompt", required=True)
    parser.add_argument("--vote-count", default="unrecorded")
    parser.add_argument("--run-reason", default="mock-run")
    parser.add_argument("--summary-out", default=".tmp/implementation-summary.md")
    args = parser.parse_args()

    safe_prompt = html.escape(args.voted_prompt)
    safe_week = html.escape(args.week)
    safe_rank = html.escape(args.candidate_rank)
    safe_issue = html.escape(args.issue_number)
    safe_votes = html.escape(args.vote_count)
    safe_reason = html.escape(args.run_reason)

    index_html = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Prompt Vote Lab Mock Run</title>
  <link rel="stylesheet" href="./style.css">
  <meta http-equiv="Content-Security-Policy" content="default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; connect-src 'none'; frame-src 'none'; object-src 'none'; base-uri 'none'; form-action 'none';">
</head>
<body>
  <main class="mock-root" aria-labelledby="mock-title">
    <p class="eyebrow">Mock implementation run</p>
    <h1 id="mock-title">Prompt Vote Lab</h1>
    <section class="card" aria-labelledby="mock-metadata-title">
      <h2 id="mock-metadata-title">Recorded candidate</h2>
      <dl>
        <div><dt>Week</dt><dd>{safe_week}</dd></div>
        <div><dt>Rank</dt><dd>{safe_rank}</dd></div>
        <div><dt>Issue</dt><dd>#{safe_issue}</dd></div>
        <div><dt>Votes</dt><dd>{safe_votes}</dd></div>
        <div><dt>Run reason</dt><dd>{safe_reason}</dd></div>
      </dl>
    </section>
    <section class="card" aria-labelledby="mock-prompt-title">
      <h2 id="mock-prompt-title">Mocked prompt</h2>
      <p>{safe_prompt}</p>
    </section>
    <p class="note">This page was generated by the mock runner. It proves the workflow can create a safe lab PR without spending API budget.</p>
  </main>
  <script src="./app.js"></script>
</body>
</html>
"""

    style_css = """:root {
  color-scheme: light;
  --bg: #f7f7f4;
  --fg: #171717;
  --muted: #66666a;
  --line: #ddddda;
  --panel: #ffffff;
  --accent: #2744d8;
}

* { box-sizing: border-box; }

body {
  min-height: 100vh;
  margin: 0;
  display: grid;
  place-items: center;
  background: var(--bg);
  color: var(--fg);
  font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
}

.mock-root {
  width: min(780px, calc(100% - 32px));
  padding: 48px 0;
}

.eyebrow {
  margin: 0 0 12px;
  color: var(--accent);
  font-size: 0.78rem;
  font-weight: 800;
  letter-spacing: 0.08em;
  text-transform: uppercase;
}

h1 {
  margin: 0 0 24px;
  font-size: clamp(2.5rem, 8vw, 5.5rem);
  line-height: 0.95;
  letter-spacing: -0.08em;
}

.card {
  margin-top: 16px;
  padding: 24px;
  border: 1px solid var(--line);
  border-radius: 24px;
  background: var(--panel);
}

h2 {
  margin: 0 0 14px;
}

p, dd, .note {
  color: var(--muted);
  line-height: 1.65;
}

dl {
  display: grid;
  gap: 10px;
  margin: 0;
}

dl div {
  display: grid;
  grid-template-columns: 120px 1fr;
  gap: 12px;
}

dt {
  color: var(--fg);
  font-weight: 800;
}

dd {
  margin: 0;
}

.note {
  margin: 18px 0 0;
}

@media (max-width: 640px) {
  dl div { grid-template-columns: 1fr; }
}
"""

    app_js = """// Mock lab run output.
// This file is intentionally inert and uses no network APIs.
"""

    (ROOT / "lab" / "index.html").write_text(index_html, encoding="utf-8")
    (ROOT / "lab" / "style.css").write_text(style_css, encoding="utf-8")
    (ROOT / "lab" / "app.js").write_text(app_js, encoding="utf-8")

    summary_path = ROOT / args.summary_out
    summary_path.parent.mkdir(parents=True, exist_ok=True)
    summary_path.write_text(
        "\n".join(
            [
                f"# Mock implementation summary for {args.week} rank {args.candidate_rank}",
                "",
                "- model: `mock-runner`",
                f"- issue: #{args.issue_number}",
                f"- votes: {args.vote_count}",
                f"- run_reason: {args.run_reason}",
                "- API cost: 0",
                "",
                "## Final message",
                "",
                "Mock lab files were written deterministically without calling the OpenAI API.",
                "",
                "## Ignored unsupported parts",
                "",
                "unrecorded",
                "",
                "## Manual test steps",
                "",
                "- Open the PR preview or published lab page.",
                "- Confirm the page shows the mock run metadata.",
                "- Confirm safety-check passed.",
            ]
        )
        + "\n",
        encoding="utf-8",
    )

    print("Wrote mock lab files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
