// Prompt Vote Lab keeps the participation layer on GitHub Issues.
// This static lab page does not fetch votes, store submissions, or use external APIs.
// Candidate data may be generated by GitHub Actions into lab/candidates.js.

const data = window.PROMPT_VOTE_LAB_CANDIDATES;
const candidateList = document.querySelector('#candidate-list');
const candidateMeta = document.querySelector('#candidate-meta');
const runResult = document.querySelector('#run-result');

function formatDate(value) {
  if (!value) return 'unrecorded';
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return 'unrecorded';
  return date.toISOString().slice(0, 10);
}

function appendText(parent, tagName, text, className) {
  const node = document.createElement(tagName);
  if (className) node.className = className;
  node.textContent = text;
  parent.append(node);
  return node;
}

function renderCandidates(candidateData) {
  if (!candidateList || !candidateData || !Array.isArray(candidateData.candidates)) return;
  if (candidateData.candidates.length === 0) return;

  candidateList.replaceChildren();

  candidateData.candidates.forEach((candidate, index) => {
    const item = document.createElement('li');

    const header = document.createElement('div');
    header.className = 'candidate-header';

    const link = document.createElement('a');
    link.href = candidate.url;
    link.textContent = `#${candidate.number} ${candidate.title}`;
    header.append(link);

    appendText(header, 'span', `${candidate.votes} vote${candidate.votes === 1 ? '' : 's'}`, 'vote-pill');
    item.append(header);

    appendText(item, 'p', candidate.expectedResult || candidate.summary || 'No expected result recorded.');

    const meta = document.createElement('p');
    meta.className = 'small-note';
    meta.textContent = `Rank ${index + 1} · ${candidate.comments} comment${candidate.comments === 1 ? '' : 's'} · updated ${formatDate(candidate.updatedAt)}`;
    item.append(meta);

    candidateList.append(item);
  });
}

function renderMeta(candidateData) {
  if (!candidateMeta || !candidateData) return;
  const generatedAt = formatDate(candidateData.generatedAt);
  const totalVotes = candidateData.selection?.totalVotes ?? 0;
  const topVotes = candidateData.selection?.topPromptVotes ?? 0;
  const decision = candidateData.selection?.selected ? 'selection threshold passed' : 'selection threshold not yet passed';
  candidateMeta.textContent = `Generated ${generatedAt}. Total votes: ${totalVotes}. Top prompt votes: ${topVotes}. ${decision}.`;

  if (runResult && candidateData.selection?.selected) {
    runResult.textContent = 'A prompt has passed the selection threshold; implementation still requires maintainer-controlled execution.';
  }
}

renderCandidates(data);
renderMeta(data);
